In [ ]:
from lib.jianji.code_csf import csf
from lib.model.resnet50 import ResNet50
from lib.loss_function.PolyLoss import PolyBCELoss
from lib.jianji.tool import *
import torch
from torch.utils.data import Dataset
from torch import nn
from torchsummary import summary
from d2l import torch as d2l
# traindSet = csf(csv_path='240000positive635000neg.pkl', mode='train')
# trainloader =  torch.utils.data.DataLoader(traindSet, batch_size=256, drop_last=True, shuffle=True)
# testset = csf(csv_path='test_valid_edited(30000).pkl', mode='valid')
# testloader = torch.utils.data.DataLoader(testset, batch_size=256, drop_last=True, shuffle=True)

In [1]:
import pandas as pd
import numpy as np
import torch
from lib.model.resnet50 import ResNet50
from lib.jianji.tool import *

In [2]:
df = pd.read_excel('for_new_step.xlsx')

In [3]:
df

4  3  2  4.1  3.1  2.1  2.2  3.2  1  2.3  ...  0.14  0.15  0.16  0.17  \
0     4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
1     4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
2     4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
3     4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
4     4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
...  .. .. ..  ...  ...  ...  ...  ... ..  ...  ...   ...   ...   ...   ...   
1663  4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
1664  4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
1665  4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
1666  4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   
1667  4  3  2    4    3    2    2    3  1    2  ...     0     0     0     0   

      0.18  0.19  0.20  0.21  0.22  0.23  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
1663     0     0     0     0     0     0  
1664     0     0     0     0     0     0  
1665     0     0     0     0     0     0  
1666     0     0     0     0     0     0  
1667     0     0     0     0     0     0  

[1668 rows x 152 columns]

In [4]:
df.describe()

4       3       2     4.1     3.1     2.1     2.2     3.2       1  \
count  1668.0  1668.0  1668.0  1668.0  1668.0  1668.0  1668.0  1668.0  1668.0   
mean      4.0     3.0     2.0     4.0     3.0     2.0     2.0     3.0     1.0   
std       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
min       4.0     3.0     2.0     4.0     3.0     2.0     2.0     3.0     1.0   
25%       4.0     3.0     2.0     4.0     3.0     2.0     2.0     3.0     1.0   
50%       4.0     3.0     2.0     4.0     3.0     2.0     2.0     3.0     1.0   
75%       4.0     3.0     2.0     4.0     3.0     2.0     2.0     3.0     1.0   
max       4.0     3.0     2.0     4.0     3.0     2.0     2.0     3.0     1.0   

          2.3  ...    0.14    0.15    0.16    0.17    0.18    0.19    0.20  \
count  1668.0  ...  1668.0  1668.0  1668.0  1668.0  1668.0  1668.0  1668.0   
mean      2.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
std       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
min       2.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
25%       2.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
50%       2.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
75%       2.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
max       2.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

         0.21    0.22    0.23  
count  1668.0  1668.0  1668.0  
mean      0.0     0.0     0.0  
std       0.0     0.0     0.0  
min       0.0     0.0     0.0  
25%       0.0     0.0     0.0  
50%       0.0     0.0     0.0  
75%       0.0     0.0     0.0  
max       0.0     0.0     0.0  

[8 rows x 152 columns]

In [48]:
feature_list = df.values.tolist()
feature = np.array(feature_list)

In [49]:
feature = feature / 4

In [50]:
feature

array([[1.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ],
       [1.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ],
       [1.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ],
       ...,
       [1.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ],
       [1.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ],
       [1.  , 0.75, 0.5 , ..., 0.  , 0.  , 0.  ]])

In [51]:
feature.shape

(1668, 152)

In [52]:
dataset = torch.from_numpy(feature)

In [53]:
dataset = dataset.float()

In [54]:
dataset

tensor([[1.0000, 0.7500, 0.5000,  ..., 0.0000, 0.0000, 0.0000],
        [1.0000, 0.7500, 0.5000,  ..., 0.0000, 0.0000, 0.0000],
        [1.0000, 0.7500, 0.5000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [1.0000, 0.7500, 0.5000,  ..., 0.0000, 0.0000, 0.0000],
        [1.0000, 0.7500, 0.5000,  ..., 0.0000, 0.0000, 0.0000],
        [1.0000, 0.7500, 0.5000,  ..., 0.0000, 0.0000, 0.0000]])

In [55]:
dataset.shape

torch.Size([1668, 152])

In [56]:
dataset = dataset.unsqueeze(1)

In [57]:
dataset.shape

torch.Size([1668, 1, 152])

In [58]:
net = ResNet50()
net.load_state_dict(torch.load('resnet50_acc_0.717.pth'))
net.eval()
output_list = []

with torch.no_grad():

    a = np.array(net(dataset).cpu())
    output_list.extend(a)

In [59]:
output_list

[array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], d

In [60]:
output_list = np.array(output_list)

In [61]:
output_list.shape

(1668, 1)

In [62]:
output_list = np.squeeze(output_list)

In [63]:
output_list.shape

(1668,)

In [64]:
output_list

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [65]:
output_list.sum()

0.0

In [66]:
a = dataset[0]

In [67]:
a

tensor([[1.0000, 0.7500, 0.5000, 1.0000, 0.7500, 0.5000, 0.5000, 0.7500, 0.2500,
         0.5000, 0.7500, 0.5000, 1.0000, 0.7500, 1.0000, 0.7500, 0.7500, 0.5000,
         0.2500, 1.0000, 0.2500, 0.7500, 0.5000, 0.5000, 0.7500, 1.0000, 0.7500,
         0.5000, 0.2500, 0.5000, 0.5000, 0.2500, 0.5000, 1.0000, 0.2500, 0.5000,
         1.0000, 0.5000, 0.5000, 0.5000, 0.2500, 0.2500, 0.7500, 1.0000, 0.2500,
         1.0000, 0.5000, 0.7500, 0.5000, 1.0000, 0.7500, 0.5000, 1.0000, 0.7500,
         0.5000, 0.2500, 0.5000, 0.7500, 0.7500, 1.0000, 0.2500, 1.0000, 0.2500,
         0.7500, 1.0000, 0.7500, 1.0000, 0.5000, 0.5000, 1.0000, 1.0000, 0.5000,
         0.5000, 1.0000, 1.0000, 0.5000, 1.0000, 0.2500, 0.2500, 0.2500, 0.7500,
         0.7500, 1.0000, 0.7500, 0.5000, 1.0000, 0.7500, 0.7500, 0.5000, 1.0000,
         0.5000, 0.5000, 0.5000, 0.7500, 1.0000, 0.2500, 1.0000, 0.5000, 0.2500,
         0.2500, 0.2500, 1.0000, 0.7500, 0.2500, 0.5000, 0.5000, 1.0000, 0.7500,
         0.7500, 0.2500, 0.5

In [68]:
a[0, 127]

tensor(0.7500)

In [69]:
len(a[0])

152

In [70]:
a[0, 127:152] = a[0, 1:26]

In [71]:
a

tensor([[1.0000, 0.7500, 0.5000, 1.0000, 0.7500, 0.5000, 0.5000, 0.7500, 0.2500,
         0.5000, 0.7500, 0.5000, 1.0000, 0.7500, 1.0000, 0.7500, 0.7500, 0.5000,
         0.2500, 1.0000, 0.2500, 0.7500, 0.5000, 0.5000, 0.7500, 1.0000, 0.7500,
         0.5000, 0.2500, 0.5000, 0.5000, 0.2500, 0.5000, 1.0000, 0.2500, 0.5000,
         1.0000, 0.5000, 0.5000, 0.5000, 0.2500, 0.2500, 0.7500, 1.0000, 0.2500,
         1.0000, 0.5000, 0.7500, 0.5000, 1.0000, 0.7500, 0.5000, 1.0000, 0.7500,
         0.5000, 0.2500, 0.5000, 0.7500, 0.7500, 1.0000, 0.2500, 1.0000, 0.2500,
         0.7500, 1.0000, 0.7500, 1.0000, 0.5000, 0.5000, 1.0000, 1.0000, 0.5000,
         0.5000, 1.0000, 1.0000, 0.5000, 1.0000, 0.2500, 0.2500, 0.2500, 0.7500,
         0.7500, 1.0000, 0.7500, 0.5000, 1.0000, 0.7500, 0.7500, 0.5000, 1.0000,
         0.5000, 0.5000, 0.5000, 0.7500, 1.0000, 0.2500, 1.0000, 0.5000, 0.2500,
         0.2500, 0.2500, 1.0000, 0.7500, 0.2500, 0.5000, 0.5000, 1.0000, 0.7500,
         0.7500, 0.2500, 0.5

In [72]:
c = a.unsqueeze(1)
# b = np.array(net(a).cpu())

In [73]:
c.shape

torch.Size([1, 1, 152])

In [74]:
b = net(c)

In [75]:
b

tensor([[0.]], grad_fn=<SigmoidBackward0>)

In [76]:
df_new = pd.read_excel('./data/train_1_0.xlsx')

In [34]:
df_new

3  3.1  1  1.1  3.2  1.2  1.3  3.3  3.4  1.4  ...  4.36  4.37  1.42  \
0     1    3  2    1    2    1    3    4    2    1  ...     3     4     3   
1     4    2  4    1    4    3    3    2    2    3  ...     2     1     4   
2     3    3  1    1    3    1    2    2    2    3  ...     1     2     1   
3     2    2  3    3    1    1    3    3    3    4  ...     4     2     4   
4     2    2  3    4    2    3    4    2    1    1  ...     4     3     2   
...  ..  ... ..  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
2590  2    4  1    3    1    1    1    3    2    2  ...     2     2     1   
2591  1    2  2    1    2    1    2    2    4    1  ...     1     4     2   
2592  3    3  4    1    4    3    4    1    3    2  ...     4     2     4   
2593  4    1  3    2    1    3    2    2    4    4  ...     1     3     4   
2594  4    1  2    1    1    4    3    4    3    1  ...     3     1     4   

      2.38  2.39  3.26  3.27  3.28  1.43  3.29  
0        3     3     4     2     1     2     4  
1        4     2     2     2     3     2     2  
2        1     1     2     4     2     4     1  
3        2     4     4     3     1     1     4  
4        3     3     2     3     4     1     3  
...    ...   ...   ...   ...   ...   ...   ...  
2590     1     1     3     4     2     4     2  
2591     3     1     1     3     4     4     3  
2592     3     3     4     4     4     1     1  
2593     1     3     2     3     2     3     3  
2594     1     2     1     1     2     3     2  

[2595 rows x 152 columns]

In [35]:
df_new = df_new/4

In [36]:
df_new

3   3.1     1   1.1   3.2   1.2   1.3   3.3   3.4   1.4  ...  4.36  \
0     0.25  0.75  0.50  0.25  0.50  0.25  0.75  1.00  0.50  0.25  ...  0.75   
1     1.00  0.50  1.00  0.25  1.00  0.75  0.75  0.50  0.50  0.75  ...  0.50   
2     0.75  0.75  0.25  0.25  0.75  0.25  0.50  0.50  0.50  0.75  ...  0.25   
3     0.50  0.50  0.75  0.75  0.25  0.25  0.75  0.75  0.75  1.00  ...  1.00   
4     0.50  0.50  0.75  1.00  0.50  0.75  1.00  0.50  0.25  0.25  ...  1.00   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2590  0.50  1.00  0.25  0.75  0.25  0.25  0.25  0.75  0.50  0.50  ...  0.50   
2591  0.25  0.50  0.50  0.25  0.50  0.25  0.50  0.50  1.00  0.25  ...  0.25   
2592  0.75  0.75  1.00  0.25  1.00  0.75  1.00  0.25  0.75  0.50  ...  1.00   
2593  1.00  0.25  0.75  0.50  0.25  0.75  0.50  0.50  1.00  1.00  ...  0.25   
2594  1.00  0.25  0.50  0.25  0.25  1.00  0.75  1.00  0.75  0.25  ...  0.75   

      4.37  1.42  2.38  2.39  3.26  3.27  3.28  1.43  3.29  
0     1.00  0.75  0.75  0.75  1.00  0.50  0.25  0.50  1.00  
1     0.25  1.00  1.00  0.50  0.50  0.50  0.75  0.50  0.50  
2     0.50  0.25  0.25  0.25  0.50  1.00  0.50  1.00  0.25  
3     0.50  1.00  0.50  1.00  1.00  0.75  0.25  0.25  1.00  
4     0.75  0.50  0.75  0.75  0.50  0.75  1.00  0.25  0.75  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2590  0.50  0.25  0.25  0.25  0.75  1.00  0.50  1.00  0.50  
2591  1.00  0.50  0.75  0.25  0.25  0.75  1.00  1.00  0.75  
2592  0.50  1.00  0.75  0.75  1.00  1.00  1.00  0.25  0.25  
2593  0.75  1.00  0.25  0.75  0.50  0.75  0.50  0.75  0.75  
2594  0.25  1.00  0.25  0.50  0.25  0.25  0.50  0.75  0.50  

[2595 rows x 152 columns]

In [ ]:
import numpy as np
from keras.models import Model
from keras.layers import Input, LSTM, RepeatVector, Masking, Embedding, Add, Dense, TimeDistributed, Reshape

# 示例数据
data = [
    [3, 3, 1, 1, 3, 1, 1, 3, 3, 1, 1, 1, 2, 1, 3, 2, 1, 4, 1, 2, 2, 1, 4, 1, 4, 1, 4, 3, 1, 2, 3, 2, 4, 2, 2, 1, 4, 4, 1, 2, 1, 1, 2, 2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 4, 1, 1, 1, 2, 3, 1, 1, 4, 4, 2, 2, 1, 4, 1, 4, 1, 4, 3, 2, 2, 4, 2, 4, 1, 4, 1, 4, 4, 2, 4, 4, 3, 2, 4, 4, 2, 4, 1, 2, 2, 3, 1, 4, 3, 1, 4, 4, 1, 1, 3, 1, 1, 2, 1, 4, 2, 4, 1, 3, 2, 3, 4, 4, 3, 1, 2, 4, 1, 3, 2, 2, 1, 2, 3, 2, 4, 4, 3, 1, 3, 2, 2, 4, 2, 1, 4, 3, 4, 4, 4, 1, 2, 2, 3, 3, 3, 1, 3],
    [1, 2, 3, 4, 1, 2, 3]
]

# 设置 max_len 为 152
max_len = 152
data_padded = np.array([seq + [0] * (max_len - len(seq)) for seq in data])

# 定义位置编码
position_indices = np.arange(max_len)
position_encoding = np.tile(position_indices, (len(data_padded), 1))

# 构建模型
input_dim = data_padded.shape[1]
encoding_dim = 50

input_seq = Input(shape=(input_dim,))
position_input = Input(shape=(input_dim,))
embedded_seq = Embedding(input_dim, 10)(input_seq)  # 使用嵌入层处理输入
position_embedding = Embedding(input_dim, 10)(position_input)  # 位置编码的嵌入层
combined_input = Add()([embedded_seq, position_embedding])  # 组合输入和位置编码

masked_input = Masking(mask_value=0)(combined_input)  # Masking layer 处理填充部分
encoded = LSTM(encoding_dim, activation='relu')(masked_input)
decoded = RepeatVector(input_dim)(encoded)
decoded = LSTM(10, return_sequences=True)(decoded)
decoded = TimeDistributed(Dense(1))(decoded)  # 使用 TimeDistributed 包装 Dense 层以逐时间步应用

autoencoder = Model([input_seq, position_input], decoded)
autoencoder.compile(optimizer='adam', loss='mse')

# 训练模型
data_padded_reshaped = data_padded.reshape((data_padded.shape[0], data_padded.shape[1], 1))
autoencoder.fit([data_padded_reshaped, position_encoding], data_padded_reshaped, epochs=100, batch_size=16, shuffle=True)

# 使用编码器部分来获得降维后的数据
encoder = Model([input_seq, position_input], encoded)
encoded_data = encoder.predict([data_padded_reshaped, position_encoding])

print("降维后的数据：", encoded_data)